[package]
name = "engine-uci"
version = "0.2.0"
edition = "2024"

[dependencies]
engine = { path = "../engine" }
chess-lib = { path = "../chess-lib" }

strum = "0.27.2"
strum_macros = "0.27.2"
vampirc-uci = "0.11.1"
log = "0.4.29"
fern = "0.7.1"
chrono = "0.4.42"
